language: node_js
node_js:
- '0.10'
after_success:
- npm run jsdoc
- cat artifacts/coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
notifications:
  slack:
    secure: ITEaTM/jpEabQ/CtdX0xLPYFK8YABcceRiDrgsyYER0Gdc4jpHtr7JQdudEKoQa0mz9DmBsxvRXvDdkUUM0MbqZVjtWGlHD9+Ckf+opPGA8FDBtu/tMVbSMBIzeS3Ekp4LHzvHRGPVltJVxu49kwsvTVfVG22UaMx6g6tAXDuEw=
deploy:
- provider: s3
  access_key_id:
    secure: SElA2AJVIBbMLtEGawJ/DkyOkWwQa4PvIs9ehh48Yf+8fryS7DtqX4V43urcOuIHEBZS/maxaTWfxaO/Q4rl2VE/LjOFavg/6s8DcTkSYL8wm0/kv3lyJiRAOxkpiVl+SmrXpk8+65/yecWFJjfbRBcTRskfpvMUuOvzk3788Dw=
  secret_access_key:
    secure: HH2pUpGP3LHe9dZEJ4B8FNfE63iv1qdk9yRM3j5lhBJcXGPn5pQDY8qHIvLNwPcUhIr7YRmTFPvmlo9i9tcYzzQKjN8q51F9fICCgro551aYgu4hzWTMkmNEH/gb+/35SXlWRs9ABMhM8KbzpO1FS9tGzjW7dP5gayGyOUulj/c=
  bucket: tsertkov-artifacts
  local-dir: artifacts
  upload-dir: dotpath-compile/master
  acl: public_read
  skip_cleanup: true
  region: eu-central-1
  endpoint: s3.eu-central-1.amazonaws.com
  on:
    branch: master
- provider: s3
  access_key_id:
    secure: SElA2AJVIBbMLtEGawJ/DkyOkWwQa4PvIs9ehh48Yf+8fryS7DtqX4V43urcOuIHEBZS/maxaTWfxaO/Q4rl2VE/LjOFavg/6s8DcTkSYL8wm0/kv3lyJiRAOxkpiVl+SmrXpk8+65/yecWFJjfbRBcTRskfpvMUuOvzk3788Dw=
  secret_access_key:
    secure: HH2pUpGP3LHe9dZEJ4B8FNfE63iv1qdk9yRM3j5lhBJcXGPn5pQDY8qHIvLNwPcUhIr7YRmTFPvmlo9i9tcYzzQKjN8q51F9fICCgro551aYgu4hzWTMkmNEH/gb+/35SXlWRs9ABMhM8KbzpO1FS9tGzjW7dP5gayGyOUulj/c=
  bucket: tsertkov-artifacts
  local-dir: artifacts
  upload-dir: dotpath-compile/develop
  acl: public_read
  skip_cleanup: true
  region: eu-central-1
  endpoint: s3.eu-central-1.amazonaws.com
  on:
    branch: develop